services:
  - type: web
    name: health-app-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn wsgi:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.5
      - key: SECRET_KEY
        generateValue: true